name: Deps & CI

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ master, 'maint/*' ]
  schedule:
    - cron: '0 0 * * 1'
  # Allow job to be triggered manually from GitHub interface
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build-linux:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    env:
      TEST_DATA_HOME: /home/runner/testdata/nitransforms-tests
    strategy:
      max-parallel: 5
      matrix:
        python-version: ['3.8', '3.9',  '3.10',  '3.11']

    steps:
    - name: Git settings (pacify DataLad)
      run: |
        git config --global user.name 'NiPreps Bot'
        git config --global user.email 'nipreps@gmail.com'
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - uses: actions/cache@v3
      id: conda
      with:
        path: |
          /usr/share/miniconda/pkgs
          /home/runner/.cache/pip
        key: python-${{ matrix.python-version }}-v1
        restore-keys: |
          python-${{ matrix.python-version }}-
    - name: Install DataLad
      run: |
        $CONDA/bin/conda install -c conda-forge git-annex datalad pip pytest
        $CONDA/bin/python -m pip install datalad-osf

    - uses: actions/cache@v3
      with:
        path: ${{ env.TEST_DATA_HOME }}
        key: data-cache-v2
        restore-keys: |
          data-cache-v2

    - name: Install test data
      run: |
        export PATH=$CONDA/bin:$PATH
        mkdir -p /home/runner/testdata
        cd /home/runner/testdata

        $CONDA/bin/datalad install https://gin.g-node.org/oesteban/nitransforms-tests
        $CONDA/bin/datalad update --merge -d nitransforms-tests/
        $CONDA/bin/datalad get -d nitransforms-tests/

    - uses: actions/checkout@v3
    - name: Install minimal dependencies
      run: |
        $CONDA/bin/pip install .[tests]
    - name: Run pytest
      run: |
        $CONDA/bin/pytest -v --cov nitransforms --cov-config .coveragerc --cov-report xml:cov.xml --doctest-modules nitransforms/

    - name: Submit code coverage
      uses: codecov/codecov-action@v3
      with:
        files: cov.xml
